{"links": {"self": {"href": "data/repositories/osrf/gzweb/issues/77/comments/41327971.json"}, "html": {"href": "#!/osrf/gzweb/issues/77#comment-41327971"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gzweb/issues/77.json"}}, "type": "issue", "id": 77, "repository": {"links": {"self": {"href": "data/repositories/osrf/gzweb.json"}, "html": {"href": "#!/osrf/gzweb"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3e2fc3f2-dc25-453b-9792-943c743d9b40}ts=1609263"}}, "type": "repository", "name": "gzweb", "full_name": "osrf/gzweb", "uuid": "{3e2fc3f2-dc25-453b-9792-943c743d9b40}"}, "title": "GZWeb can't find local models"}, "content": {"raw": "No the issue have been resolved for long! You can close the issue, thank you!", "markup": "markdown", "html": "<p>No the issue have been resolved for long! You can close the issue, thank you!</p>", "type": "rendered"}, "created_on": "2017-11-20T17:44:45.287286+00:00", "user": {"display_name": "Chris Papadopoulos", "uuid": "{9075cb06-cef1-40cc-baf0-d1f41e497846}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B9075cb06-cef1-40cc-baf0-d1f41e497846%7D"}, "html": {"href": "https://bitbucket.org/%7B9075cb06-cef1-40cc-baf0-d1f41e497846%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:c1fee684-3a72-48a3-bc46-170a53cbc274/ab888047-9c72-4434-a146-8d3f3fdb8af5/128"}}, "nickname": "pap-x", "type": "user", "account_id": "557058:c1fee684-3a72-48a3-bc46-170a53cbc274"}, "updated_on": null, "type": "issue_comment", "id": 41327971}