{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/gzweb.json"}, "html": {"href": "#!/osrf/gzweb"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3e2fc3f2-dc25-453b-9792-943c743d9b40}ts=1609263"}}, "type": "repository", "name": "gzweb", "full_name": "osrf/gzweb", "uuid": "{3e2fc3f2-dc25-453b-9792-943c743d9b40}"}, "links": {"attachments": {"href": "data/repositories/osrf/gzweb/issues/126/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/gzweb/issues/126.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gzweb/issues/126/watch"}, "comments": {"href": "data/repositories/osrf/gzweb/issues/126/comments_page=1.json"}, "html": {"href": "#!/osrf/gzweb/issues/126/when-re-running-gzweb-on-a-port-that-was"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gzweb/issues/126/vote"}}, "reporter": {"display_name": "Mohamd Ayman", "uuid": "{72e87935-5983-4f36-8505-0c88a6493930}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B72e87935-5983-4f36-8505-0c88a6493930%7D"}, "html": {"href": "https://bitbucket.org/%7B72e87935-5983-4f36-8505-0c88a6493930%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:53a1879d-b572-46c9-97d3-8fa52b2ff8a7/d5d765e0-f86b-4c0d-93ed-c67429f1f465/128"}}, "nickname": "Mohamd Ayman", "type": "user", "account_id": "557058:53a1879d-b572-46c9-97d3-8fa52b2ff8a7"}, "title": "When re-running gzweb on a port that was used before.", "component": null, "votes": 0, "watches": 1, "content": {"raw": "When re-running gzweb on a port that was used before while there was no gzserver running causes this error.\r\n\r\n```\r\nevents.js:160\r\n      throw er; // Unhandled 'error' event\r\n      ^\r\n\r\nError: listen EADDRINUSE :::7681\r\n    at Object.exports._errnoException (util.js:896:11)\r\n    at exports._exceptionWithHostPort (util.js:919:20)\r\n    at Server._listen2 (net.js:1246:14)\r\n    at listen (net.js:1282:10)\r\n    at Server.listen (net.js:1378:5)\r\n    at Object.<anonymous> (/home/mh/ws/gzweb/orggzweb/gzbridge/ws_server.js:37:8)\r\n    at Module._compile (module.js:541:32)\r\n    at Object.Module._extensions..js (module.js:550:10)\r\n    at Module.load (module.js:456:32)\r\n    at tryModuleLoad (module.js:415:12)\r\n```", "markup": "markdown", "html": "<p>When re-running gzweb on a port that was used before while there was no gzserver running causes this error.</p>\n<div class=\"codehilite\"><pre><span></span>events.js:160\n      throw er; // Unhandled &#39;error&#39; event\n      ^\n\nError: listen EADDRINUSE :::7681\n    at Object.exports._errnoException (util.js:896:11)\n    at exports._exceptionWithHostPort (util.js:919:20)\n    at Server._listen2 (net.js:1246:14)\n    at listen (net.js:1282:10)\n    at Server.listen (net.js:1378:5)\n    at Object.&lt;anonymous&gt; (/home/mh/ws/gzweb/orggzweb/gzbridge/ws_server.js:37:8)\n    at Module._compile (module.js:541:32)\n    at Object.Module._extensions..js (module.js:550:10)\n    at Module.load (module.js:456:32)\n    at tryModuleLoad (module.js:415:12)\n</pre></div>", "type": "rendered"}, "assignee": null, "state": "new", "version": null, "edited_on": null, "created_on": "2017-10-30T06:58:45.650131+00:00", "milestone": null, "updated_on": "2017-12-01T01:44:59.020065+00:00", "type": "issue", "id": 126}