{"pagelen": 100, "values": [{"links": {"self": {"href": "data/repositories/osrf/gzweb/issues/167/comments/53987202.json"}, "html": {"href": "#!/osrf/gzweb/issues/167#comment-53987202"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gzweb/issues/167.json"}}, "type": "issue", "id": 167, "repository": {"links": {"self": {"href": "data/repositories/osrf/gzweb.json"}, "html": {"href": "#!/osrf/gzweb"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3e2fc3f2-dc25-453b-9792-943c743d9b40}ts=1609263"}}, "type": "repository", "name": "gzweb", "full_name": "osrf/gzweb", "uuid": "{3e2fc3f2-dc25-453b-9792-943c743d9b40}"}, "title": "urdf model is not able to be loaded by gzweb"}, "content": {"raw": "I wouldn't expect the robot to look like that if it were a problem with the URDF though. It seems to be more of a problem reading the underlying mesh file (collada / obj / stl). You could try loading a simple SDF with just the mesh you have to see if the problem persists. Also, have you checked that it is loaded properly with `gzclient` (i.e. `gazebo`)?", "markup": "markdown", "html": "<p>I wouldn't expect the robot to look like that if it were a problem with the URDF though. It seems to be more of a problem reading the underlying mesh file (collada / obj / stl). You could try loading a simple SDF with just the mesh you have to see if the problem persists. Also, have you checked that it is loaded properly with <code>gzclient</code> (i.e. <code>gazebo</code>)?</p>", "type": "rendered"}, "created_on": "2019-09-19T17:00:05.412848+00:00", "user": {"display_name": "Louise Poubel", "uuid": "{5cfa2075-477b-4ded-bdb9-8d2479544ec4}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D"}, "html": {"href": "https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:6ff86fcb-b7ab-44a5-b8a6-f6d9cae8b6e8/7d903d90-c5ea-4182-b7ef-0d467e9e1c74/128"}}, "nickname": "chapulina", "type": "user", "account_id": "557058:6ff86fcb-b7ab-44a5-b8a6-f6d9cae8b6e8"}, "updated_on": null, "type": "issue_comment", "id": 53987202}, {"links": {"self": {"href": "data/repositories/osrf/gzweb/issues/167/comments/53987754.json"}, "html": {"href": "#!/osrf/gzweb/issues/167#comment-53987754"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gzweb/issues/167.json"}}, "type": "issue", "id": 167, "repository": {"links": {"self": {"href": "data/repositories/osrf/gzweb.json"}, "html": {"href": "#!/osrf/gzweb"}, "avatar": {"href": "data/bytebucket.org/ravatar/{3e2fc3f2-dc25-453b-9792-943c743d9b40}ts=1609263"}}, "type": "repository", "name": "gzweb", "full_name": "osrf/gzweb", "uuid": "{3e2fc3f2-dc25-453b-9792-943c743d9b40}"}, "title": "urdf model is not able to be loaded by gzweb"}, "content": {"raw": "Hi Louise, Thanks for your reply. I also run the gazebo, and the robot model is fine in gzclient. And I tried to convert the urdf file to sdf file,  I saw in the output of \u201cnpm run deploy --- -m local\u201c, it processes the .sdf file, but the model still looks like in the same way. \n\n\u200c", "markup": "markdown", "html": "<p>Hi Louise, Thanks for your reply. I also run the gazebo, and the robot model is fine in gzclient. And I tried to convert the urdf file to sdf file,  I saw in the output of \u201cnpm run deploy --- -m local\u201c, it processes the .sdf file, but the model still looks like in the same way. </p>\n<p>\u200c</p>", "type": "rendered"}, "created_on": "2019-09-19T17:50:18.257851+00:00", "user": {"display_name": "Xu Tao", "uuid": "{abb5d88f-1f75-4d21-afdf-5065f29ed4df}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Babb5d88f-1f75-4d21-afdf-5065f29ed4df%7D"}, "html": {"href": "https://bitbucket.org/%7Babb5d88f-1f75-4d21-afdf-5065f29ed4df%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/e585ef10d69c6ad325fd273d0a176f07d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsXT-3.png"}}, "nickname": "Xu Tao", "type": "user", "account_id": "5d8356289581710c3032b56c"}, "updated_on": "2019-09-23T12:28:23.081196+00:00", "type": "issue_comment", "id": 53987754}], "page": 1, "size": 2}